package com.codeclinic.gateway.feedback;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * recommendations 테이블 JDBC 엔티티.
 * id는 BIGSERIAL — DB가 자동 생성하므로 null로 빌드, INSERT 후 Spring Data JDBC가 설정.
 */
@Table("recommendations")
@Getter
@Builder
@AllArgsConstructor
public class Recommendation {

    @Id
    private final Long id;  // null before INSERT; BIGSERIAL generated by DB

    @Column("attack_log_id")
    private final UUID attackLogId;

    @Column("cwe_type")
    private final String cweType;

    @Column("file_path")
    private final String filePath;

    @Column("line_number")
    private final Integer lineNumber;

    private final String pattern;    // Semgrep check_id (탐지 규칙 식별자)
    private final String suggestion; // 권고 내용 (RecommendationBuilder 생성)

    @Column("created_at")
    private final Instant createdAt;
}
